parser: "babel-eslint" # for class properties
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: "module"

extends: "google"
plugins:
  - "react"
rules:
  object-curly-spacing:
    - 2
    - "always"
  camelcase: 0
  max-len:
    - 2
    - ignoreTemplateLiterals: true
    - ignoreUrls: true
  new-cap: 0 # immutable.js
  react/jsx-uses-vars: 1