parser: "babel-eslint" # for class properties
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: "module"

extends: "google"
plugins:
  - "react"
rules:
  camelcase: 0
  max-len:
    - 2
    - ignoreTemplateLiterals: true
    - ignoreUrls: true
  react/jsx-uses-vars: 1